var hierarchy =
[
    [ "otbr::DBus::ActiveScanResult", "d2/da8/structotbr_1_1DBus_1_1ActiveScanResult.html", null ],
    [ "otbr::AgentInstance", "d3/d79/classotbr_1_1AgentInstance.html", null ],
    [ "AvahiTimeout", "db/dfa/structAvahiTimeout.html", null ],
    [ "AvahiWatch", "de/d3f/structAvahiWatch.html", null ],
    [ "otbr::BackboneRouter::BackboneAgent", "da/d5a/classotbr_1_1BackboneRouter_1_1BackboneAgent.html", null ],
    [ "otbr::BorderAgent", "d4/dfd/classotbr_1_1BorderAgent.html", null ],
    [ "otbr::DBus::ChannelQuality", "dd/d1a/structotbr_1_1DBus_1_1ChannelQuality.html", null ],
    [ "otbr::DBus::ChildInfo", "db/d06/structotbr_1_1DBus_1_1ChildInfo.html", null ],
    [ "otbr::rest::Connection", "d4/db3/classotbr_1_1rest_1_1Connection.html", null ],
    [ "otbr::Crc16", "d6/d8f/classotbr_1_1Crc16.html", null ],
    [ "otbr::DBus::DBusMessageDeleter", "da/dac/structotbr_1_1DBus_1_1DBusMessageDeleter.html", null ],
    [ "otbr::DBus::DBusMessageIterFor< I, N, FieldTypes >", "d7/d52/classotbr_1_1DBus_1_1DBusMessageIterFor.html", null ],
    [ "otbr::DBus::DBusMessageIterFor< 1, N, FieldTypes... >", "d5/d50/classotbr_1_1DBus_1_1DBusMessageIterFor_3_011_00_01N_00_01FieldTypes_8_8_8_01_4.html", null ],
    [ "otbr::DBus::DBusObject", "da/d4d/classotbr_1_1DBus_1_1DBusObject.html", [
      [ "otbr::DBus::DBusThreadObject", "de/d73/classotbr_1_1DBus_1_1DBusThreadObject.html", null ]
    ] ],
    [ "otbr::DBus::DBusRequest", "d0/d92/classotbr_1_1DBus_1_1DBusRequest.html", null ],
    [ "otbr::DBus::DBusTypeTrait< T >", "d1/d41/structotbr_1_1DBus_1_1DBusTypeTrait.html", null ],
    [ "otbr::DBus::DBusTypeTrait< ActiveScanResult >", "dd/d8a/structotbr_1_1DBus_1_1DBusTypeTrait_3_01ActiveScanResult_01_4.html", null ],
    [ "otbr::DBus::DBusTypeTrait< ChannelQuality >", "d7/dcb/structotbr_1_1DBus_1_1DBusTypeTrait_3_01ChannelQuality_01_4.html", null ],
    [ "otbr::DBus::DBusTypeTrait< ChildInfo >", "de/d83/structotbr_1_1DBus_1_1DBusTypeTrait_3_01ChildInfo_01_4.html", null ],
    [ "otbr::DBus::DBusTypeTrait< ExternalRoute >", "d0/d04/structotbr_1_1DBus_1_1DBusTypeTrait_3_01ExternalRoute_01_4.html", null ],
    [ "otbr::DBus::DBusTypeTrait< int16_t >", "da/de7/structotbr_1_1DBus_1_1DBusTypeTrait_3_01int16__t_01_4.html", null ],
    [ "otbr::DBus::DBusTypeTrait< int32_t >", "d4/d33/structotbr_1_1DBus_1_1DBusTypeTrait_3_01int32__t_01_4.html", null ],
    [ "otbr::DBus::DBusTypeTrait< int64_t >", "d5/d1c/structotbr_1_1DBus_1_1DBusTypeTrait_3_01int64__t_01_4.html", null ],
    [ "otbr::DBus::DBusTypeTrait< int8_t >", "d1/d13/structotbr_1_1DBus_1_1DBusTypeTrait_3_01int8__t_01_4.html", null ],
    [ "otbr::DBus::DBusTypeTrait< Ip6Prefix >", "d6/d18/structotbr_1_1DBus_1_1DBusTypeTrait_3_01Ip6Prefix_01_4.html", null ],
    [ "otbr::DBus::DBusTypeTrait< IpCounters >", "d0/dfe/structotbr_1_1DBus_1_1DBusTypeTrait_3_01IpCounters_01_4.html", null ],
    [ "otbr::DBus::DBusTypeTrait< LeaderData >", "df/d1a/structotbr_1_1DBus_1_1DBusTypeTrait_3_01LeaderData_01_4.html", null ],
    [ "otbr::DBus::DBusTypeTrait< LinkModeConfig >", "de/d7a/structotbr_1_1DBus_1_1DBusTypeTrait_3_01LinkModeConfig_01_4.html", null ],
    [ "otbr::DBus::DBusTypeTrait< MacCounters >", "d8/d87/structotbr_1_1DBus_1_1DBusTypeTrait_3_01MacCounters_01_4.html", null ],
    [ "otbr::DBus::DBusTypeTrait< NeighborInfo >", "d9/d42/structotbr_1_1DBus_1_1DBusTypeTrait_3_01NeighborInfo_01_4.html", null ],
    [ "otbr::DBus::DBusTypeTrait< std::array< uint8_t, SIZE > >", "d7/d53/structotbr_1_1DBus_1_1DBusTypeTrait_3_01std_1_1array_3_01uint8__t_00_01SIZE_01_4_01_4.html", null ],
    [ "otbr::DBus::DBusTypeTrait< std::string >", "d1/de2/structotbr_1_1DBus_1_1DBusTypeTrait_3_01std_1_1string_01_4.html", null ],
    [ "otbr::DBus::DBusTypeTrait< std::vector< ChannelQuality > >", "d9/d90/structotbr_1_1DBus_1_1DBusTypeTrait_3_01std_1_1vector_3_01ChannelQuality_01_4_01_4.html", null ],
    [ "otbr::DBus::DBusTypeTrait< std::vector< ChildInfo > >", "df/de4/structotbr_1_1DBus_1_1DBusTypeTrait_3_01std_1_1vector_3_01ChildInfo_01_4_01_4.html", null ],
    [ "otbr::DBus::DBusTypeTrait< std::vector< ExternalRoute > >", "d9/d1d/structotbr_1_1DBus_1_1DBusTypeTrait_3_01std_1_1vector_3_01ExternalRoute_01_4_01_4.html", null ],
    [ "otbr::DBus::DBusTypeTrait< std::vector< NeighborInfo > >", "dd/daa/structotbr_1_1DBus_1_1DBusTypeTrait_3_01std_1_1vector_3_01NeighborInfo_01_4_01_4.html", null ],
    [ "otbr::DBus::DBusTypeTrait< std::vector< uint8_t > >", "de/dac/structotbr_1_1DBus_1_1DBusTypeTrait_3_01std_1_1vector_3_01uint8__t_01_4_01_4.html", null ],
    [ "otbr::DBus::DBusTypeTrait< uint16_t >", "d7/dfa/structotbr_1_1DBus_1_1DBusTypeTrait_3_01uint16__t_01_4.html", null ],
    [ "otbr::DBus::DBusTypeTrait< uint32_t >", "d7/dbd/structotbr_1_1DBus_1_1DBusTypeTrait_3_01uint32__t_01_4.html", null ],
    [ "otbr::DBus::DBusTypeTrait< uint64_t >", "d0/dd7/structotbr_1_1DBus_1_1DBusTypeTrait_3_01uint64__t_01_4.html", null ],
    [ "otbr::DBus::DBusTypeTrait< uint8_t >", "d3/da2/structotbr_1_1DBus_1_1DBusTypeTrait_3_01uint8__t_01_4.html", null ],
    [ "otbr::rest::DiagInfo", "da/dfd/structotbr_1_1rest_1_1DiagInfo.html", null ],
    [ "otbr::DBus::ElementType< I, FieldTypes >", "d1/d8f/structotbr_1_1DBus_1_1ElementType.html", null ],
    [ "otbr::EventEmitter", "dd/dcb/classotbr_1_1EventEmitter.html", [
      [ "otbr::Ncp::Controller", "da/d6a/classotbr_1_1Ncp_1_1Controller.html", [
        [ "otbr::Ncp::ControllerOpenThread", "db/d17/classotbr_1_1Ncp_1_1ControllerOpenThread.html", null ]
      ] ]
    ] ],
    [ "otbr::DBus::ExternalRoute", "de/d00/structotbr_1_1DBus_1_1ExternalRoute.html", null ],
    [ "otbr::InstanceParams", "d2/dd0/classotbr_1_1InstanceParams.html", null ],
    [ "otbr::Ip6Address", "d2/dfe/classotbr_1_1Ip6Address.html", null ],
    [ "otbr::DBus::Ip6Prefix", "da/d56/structotbr_1_1DBus_1_1Ip6Prefix.html", null ],
    [ "otbr::Ip6Prefix", "da/d3a/classotbr_1_1Ip6Prefix.html", null ],
    [ "otbr::DBus::IpCounters", "da/d27/structotbr_1_1DBus_1_1IpCounters.html", null ],
    [ "kPollTimeout", null, [
      [ "otbr::DBus::DBusAgent", "d3/dd6/structotbr_1_1DBus_1_1DBusAgent.html", null ]
    ] ],
    [ "otbr::DBus::LeaderData", "dd/d1d/structotbr_1_1DBus_1_1LeaderData.html", null ],
    [ "otbr::DBus::LinkModeConfig", "d1/d82/structotbr_1_1DBus_1_1LinkModeConfig.html", null ],
    [ "otbr::MacAddress", "db/d8f/classotbr_1_1MacAddress.html", null ],
    [ "otbr::DBus::MacCounters", "d6/d98/structotbr_1_1DBus_1_1MacCounters.html", null ],
    [ "otbr::BackboneRouter::NdProxyManager", "d8/d58/classotbr_1_1BackboneRouter_1_1NdProxyManager.html", null ],
    [ "otbr::DBus::NeighborInfo", "d2/d47/structotbr_1_1DBus_1_1NeighborInfo.html", null ],
    [ "otbr::rest::NodeInfo", "d6/dbf/structotbr_1_1rest_1_1NodeInfo.html", null ],
    [ "otbr::DBus::OnMeshPrefix", "d5/d02/structotbr_1_1DBus_1_1OnMeshPrefix.html", null ],
    [ "otbr::Web::OpenThreadClient", "d3/d3f/classotbr_1_1Web_1_1OpenThreadClient.html", null ],
    [ "otbr::rest::Parser", "d7/def/classotbr_1_1rest_1_1Parser.html", null ],
    [ "otbr::Mdns::Poller", "d5/d23/classotbr_1_1Mdns_1_1Poller.html", null ],
    [ "otbr::Psk::Pskc", "d6/dad/classotbr_1_1Psk_1_1Pskc.html", null ],
    [ "otbr::Mdns::Publisher", "da/ddc/classotbr_1_1Mdns_1_1Publisher.html", [
      [ "otbr::Mdns::PublisherAvahi", "db/dc6/classotbr_1_1Mdns_1_1PublisherAvahi.html", null ],
      [ "otbr::Mdns::PublisherMDnsSd", "de/d29/classotbr_1_1Mdns_1_1PublisherMDnsSd.html", null ]
    ] ],
    [ "otbr::rest::Request", "da/df0/classotbr_1_1rest_1_1Request.html", null ],
    [ "otbr::rest::Resource", "d7/d6e/classotbr_1_1rest_1_1Resource.html", null ],
    [ "otbr::rest::Response", "d2/db0/classotbr_1_1rest_1_1Response.html", null ],
    [ "otbr::rest::RestWebServer", "d8/d5d/classotbr_1_1rest_1_1RestWebServer.html", null ],
    [ "SimpleWeb::Server< T >", "df/d24/classSimpleWeb_1_1Server.html", null ],
    [ "otbr::SteeringData", "d6/de8/classotbr_1_1SteeringData.html", null ],
    [ "otbr::DBus::ThreadApiDBus", "df/dcc/classotbr_1_1DBus_1_1ThreadApiDBus.html", null ],
    [ "otbr::agent::ThreadHelper", "d4/d44/classotbr_1_1agent_1_1ThreadHelper.html", null ],
    [ "otbr::Tlv", "d0/d02/classotbr_1_1Tlv.html", null ],
    [ "otbr::ubus::UbusServer", "d9/dea/classotbr_1_1ubus_1_1UbusServer.html", null ],
    [ "otbr::Web::WebServer", "d6/d83/classotbr_1_1Web_1_1WebServer.html", null ],
    [ "otbr::Web::WpanNetworkInfo", "d9/dc3/structotbr_1_1Web_1_1WpanNetworkInfo.html", null ],
    [ "otbr::Web::WpanService", "d3/d46/classotbr_1_1Web_1_1WpanService.html", null ]
];