#! /bin/sh
#
#  Copyright (c) 2017, The OpenThread Authors.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#
#   Description:
#       This script watches and radvd configuration changes.
#
RADVD_CONFD=/etc/radvd.d
RADVD_CONF=/etc/radvd.conf
THREAD_CONF=/etc/radvd.d/thread.conf
PID_FILE=/var/run/otbr-radvd-watcher.pid

set -x

if ! which inotifywait; then
    >&2 echo 'No inotifywait found!'
    exit 1
fi

if test -f $PID_FILE; then
    >&2 echo 'Another watcher already running!'
    exit 1
fi

# Get the pgid for stopping this daemon.
ps -o pgid -h -p $$ > $PID_FILE

release_lock()
{
    test ! -f $PID_FILE || rm -v $PID_FILE
    exit 0
}

trap release_lock INT TERM EXIT

while true; do
    # Put these creation here in case files are deleted.
    test -d $RADVD_CONFD || mkdir -p $RADVD_CONFD
    test -f $THREAD_CONF || touch $THREAD_CONF

    echo -n 'Regenerating radvd configuration...'
    cat $RADVD_CONFD/*.conf > $RADVD_CONF
    echo 'done'

    echo -n 'Restarting radvd...'
    if which systemctl; then
        systemctl restart radvd
    elif which service; then
        service radvd restart
    fi
    echo 'done'

    echo -n 'Waiting for changes...'
    inotifywait -e modify $THREAD_CONF || {
        echo "error $?!"
        sleep 5
        continue
    }
    echo 'Thread configuration changed.'

    # delay for file changes finish.
    sleep 5
done
