#!/bin/bash
#
#  Copyright (c) 2020, The OpenThread Authors.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#

set -euxo pipefail

readonly OPENWRT_VERSION=openwrt-18.06
readonly OPENWRT_GIT_REMOTE=https://github.com/openwrt/openwrt.git
readonly PACKAGE_NAME=openthread-br

do_prepare()
{
    if [ ! -d "${OPENWRT_TOP_SRCDIR}" ]; then
        git clone -b "${OPENWRT_VERSION}" --depth 1 --recurse-submodules --shallow-submodules "${OPENWRT_GIT_REMOTE}" "${OPENWRT_TOP_SRCDIR}"
    fi

    cp etc/openwrt/openthread-br/.config "${OPENWRT_TOP_SRCDIR}"

    if ! grep -q openthread "${OPENWRT_TOP_SRCDIR}/feeds.conf"; then
        echo src-link openthread "$(pwd)/etc/openwrt" >> ${OPENWRT_TOP_SRCDIR}/feeds.conf
    fi

    (cd ${OPENWRT_TOP_SRCDIR} \
        && ./scripts/feeds update openthread \
        && ./scripts/feeds install -a \
        && echo 'y' | make oldconfig \
        && make -j${BUILD_JOBS} tools/install \
        && make -j${BUILD_JOBS} toolchain/install)
}

do_build()
{
    (cd ${OPENWRT_TOP_SRCDIR} \
        && make -j${BUILD_JOBS} package/${PACKAGE_NAME}/compile \
        && find * -name "${PACKAGE_NAME}*.ipk" | grep "${PACKAGE_NAME}")
}

main()
{
    if [[ $# = 0 ]]; then
        do_prepare
        do_build
    else
        case "$1" in
            prepare)
                do_prepare
                ;;
            build)
                do_build
                ;;
        esac
    fi
}

main "$@"
